typography_spectrum: 0.8009306394960731
content_rating:
  adult: false
color:
  saturation: 0.4307198
  lightness: 0.8979006
  brandStrength: 0.9562548
  rhythmicContrast: 0.08736137
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.4748596765566617
author:
  name: David Brotnov
  email: dvdbrotnov@gmail.com
name: 'Notes from Above Ground '
title: Welcome
description: to my playground..
