layout_spectrum: 0.5537175
typography_spectrum: 0.02556969
color:
  saturation: 0.4307198
  lightness: 0.8979006
  brandStrength: 0.9562548
  rhythmicContrast: 0.08736137
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: 'Notes from Above Ground '
